apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: cloud-app
        image: daniellupacescu/cloud-app:latest  
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"  
            cpu: "100m"      
          limits:
            memory: "128Mi"  
            cpu: "250m"     
